
package visao;

import Vo.Hospede;
import dao.HospedeDao;
import factory.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;



public class CadastrarHospede extends javax.swing.JInternalFrame {
private Connection connection;
    /**
     * Creates new form GUICadProduto
     */
    public CadastrarHospede() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlQuantidade3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlValorCusto = new javax.swing.JLabel();
        jlQuantidade = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        Combo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jlNome1 = new javax.swing.JLabel();
        jlValorCusto1 = new javax.swing.JLabel();
        jlQuantidade1 = new javax.swing.JLabel();
        jtNome1 = new javax.swing.JTextField();
        jtValorCusto2 = new javax.swing.JTextField();
        jtQuantidade1 = new javax.swing.JTextField();
        javax.swing.JComboBox<Object> jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtValorCusto3 = new javax.swing.JTextField();
        jlQuantidade2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtData = new javax.swing.JFormattedTextField();
        jtSenha = new javax.swing.JPasswordField();
        jtCPF = new javax.swing.JFormattedTextField();
        jtTelefone = new javax.swing.JFormattedTextField();
        jtCelular = new javax.swing.JFormattedTextField();
        jtRG = new javax.swing.JFormattedTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        jlQuantidade3.setText("Celular:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Cadastro de Hospede");

        jLayeredPane1.setBackground(new java.awt.Color(148, 246, 7));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 213, 45)));

        jlNome.setText("Nome:");
        jLayeredPane1.add(jlNome);
        jlNome.setBounds(20, 10, 60, 14);

        jlValorCusto.setText("CPF:");
        jLayeredPane1.add(jlValorCusto);
        jlValorCusto.setBounds(20, 50, 100, 14);

        jlQuantidade.setText("Celular:");
        jLayeredPane1.add(jlQuantidade);
        jlQuantidade.setBounds(250, 90, 100, 20);
        jLayeredPane1.add(jtNome);
        jtNome.setBounds(70, 10, 450, 30);

        Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new Object[] { "AC", "AL", "AP"
            , "AM", "BA", "CE", "DF", "ES", "GO", "MA"
            , "MT", "MS", "MG", "PA", "PB", "PR", "PE",
            "PI", "RR", "RO", "RJ", "RN", "RS", "SC", "SC"
            , "SP", "SE", "TO"}));
Combo.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        ComboActionPerformed(evt);
    }
    });
    jLayeredPane1.add(Combo);
    Combo.setBounds(400, 190, 70, 20);

    jLabel1.setText("Estado:");
    jLayeredPane1.add(jLabel1);
    jLabel1.setBounds(350, 190, 60, 20);

    jLabel2.setText("Data de Nacimento:");
    jLayeredPane1.add(jLabel2);
    jLabel2.setBounds(10, 90, 110, 20);

    jLayeredPane3.setBackground(new java.awt.Color(148, 246, 7));
    jLayeredPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 213, 45)));

    jlNome1.setText("Nome:");
    jLayeredPane3.add(jlNome1);
    jlNome1.setBounds(20, 10, 60, 14);

    jlValorCusto1.setText("CPF:");
    jLayeredPane3.add(jlValorCusto1);
    jlValorCusto1.setBounds(20, 50, 100, 14);

    jlQuantidade1.setText("RG:");
    jLayeredPane3.add(jlQuantidade1);
    jlQuantidade1.setBounds(310, 50, 100, 14);
    jLayeredPane3.add(jtNome1);
    jtNome1.setBounds(70, 10, 300, 20);
    jLayeredPane3.add(jtValorCusto2);
    jtValorCusto2.setBounds(120, 90, 110, 20);
    jLayeredPane3.add(jtQuantidade1);
    jtQuantidade1.setBounds(340, 50, 210, 20);

    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new Object[] { "AC", "AL", "AP"
        , "AM", "BA", "CE", "DF", "ES", "GO", "MA"
        , "MT", "MS", "MG", "PA", "PB", "PR", "PE",
        "PI", "RR", "RO", "RJ", "RN", "RS", "SC", "SC"
        , "SP", "SE", "TO"}));
jComboBox2.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
    jComboBox2ActionPerformed(evt);
    }
    });
    jLayeredPane3.add(jComboBox2);
    jComboBox2.setBounds(470, 10, 70, 20);

    jLabel3.setText("Estado:");
    jLayeredPane3.add(jLabel3);
    jLabel3.setBounds(400, 10, 50, 20);

    jLabel4.setText("Data de Nacimento:");
    jLayeredPane3.add(jLabel4);
    jLabel4.setBounds(20, 90, 100, 20);
    jLayeredPane3.add(jtValorCusto3);
    jtValorCusto3.setBounds(50, 50, 240, 20);

    jLayeredPane1.add(jLayeredPane3);
    jLayeredPane3.setBounds(0, 0, 0, 0);

    jlQuantidade2.setText("RG:");
    jLayeredPane1.add(jlQuantidade2);
    jlQuantidade2.setBounds(310, 50, 100, 20);

    jLabel5.setText("Telefone:");
    jLayeredPane1.add(jLabel5);
    jLabel5.setBounds(10, 130, 70, 30);

    jLabel6.setText("Email:");
    jLayeredPane1.add(jLabel6);
    jLabel6.setBounds(260, 130, 50, 30);
    jLayeredPane1.add(jtEmail);
    jtEmail.setBounds(310, 130, 270, 30);

    jLabel7.setText("Senha:");
    jLayeredPane1.add(jLabel7);
    jLabel7.setBounds(10, 184, 40, 20);

    try {
        jtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
    } catch (java.text.ParseException ex) {
        ex.printStackTrace();
    }
    jtData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    jLayeredPane1.add(jtData);
    jtData.setBounds(150, 90, 80, 20);
    jLayeredPane1.add(jtSenha);
    jtSenha.setBounds(60, 180, 260, 30);

    try {
        jtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
    } catch (java.text.ParseException ex) {
        ex.printStackTrace();
    }
    jtCPF.setName(""); // NOI18N
    jLayeredPane1.add(jtCPF);
    jtCPF.setBounds(50, 50, 240, 30);

    try {
        jtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
    } catch (java.text.ParseException ex) {
        ex.printStackTrace();
    }
    jtTelefone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    jLayeredPane1.add(jtTelefone);
    jtTelefone.setBounds(90, 130, 160, 30);

    try {
        jtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
    } catch (java.text.ParseException ex) {
        ex.printStackTrace();
    }
    jtCelular.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jtCelularActionPerformed(evt);
        }
    });
    jLayeredPane1.add(jtCelular);
    jtCelular.setBounds(330, 90, 160, 30);

    try {
        jtRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
    } catch (java.text.ParseException ex) {
        ex.printStackTrace();
    }
    jtRG.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jtRGActionPerformed(evt);
        }
    });
    jLayeredPane1.add(jtRG);
    jtRG.setBounds(340, 50, 180, 30);

    jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    jbCadastrar.setBackground(new java.awt.Color(102, 255, 0));
    jbCadastrar.setForeground(new java.awt.Color(255, 255, 255));
    jbCadastrar.setText("cadastrar");
    jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbCadastrarActionPerformed(evt);
        }
    });
    jLayeredPane2.add(jbCadastrar);
    jbCadastrar.setBounds(30, 20, 110, 23);

    jbLimpar.setBackground(new java.awt.Color(102, 255, 0));
    jbLimpar.setForeground(new java.awt.Color(255, 255, 255));
    jbLimpar.setText("limpar");
    jbLimpar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbLimparActionPerformed(evt);
        }
    });
    jLayeredPane2.add(jbLimpar);
    jbLimpar.setBounds(450, 20, 110, 23);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(4, 4, 4)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar() {
        
            Hospede pVO = new Hospede();
            pVO.setNome(jtNome.getText());
            pVO.setCpf(jtCPF.getText());
            pVO.setRg(jtRG.getText());
            pVO.setAno(jtData.getText());
             pVO.setCelular(jtCelular.getText());
              pVO.setTelefone(jtTelefone.getText());
               pVO.setSenha(jtSenha.getText()); 
               pVO.setEmail(jtEmail.getText());
                pVO.setEstado((String) Combo.getSelectedItem());
               
            
            //Enviando o objeto pVO para o banco de dados
            HospedeDao dao = new HospedeDao();
dao.registrarHospede(pVO);
            //fecha catch
        
    }//fecha método cadastrar
    //fecha método cadastrar
        
    private void limpar() {
        jtNome.setText("");
        jtSenha.setText("");
        jtRG.setText("");
         jtCPF.setText("");
          jtData.setText("");
           jtCelular.setText("");
            jtTelefone.setText("");
             jtEmail.setText("");
              Combo.setSelectedItem("AC");
    }//fecha método limpar
      public void buscarHospede(String id) {
        
        this.connection = new ConnectionFactory().getConnection();
        String sql = "";
       
        sql = "select rg,nome,ano_nasc,email,celular,telefone,senhar,estado from hospede where cpf= '" + id + "'";
        
        try {
            PreparedStatement stm = connection.prepareStatement(sql);
            ResultSet res = stm.executeQuery();
            
           
            while (res.next()) {
                
                String tx1 = (res.getString(1));
                
                String tx2 = (res.getString(2));
                
                String tx3 = (res.getString(3));
                
                String tx4 = (res.getString(4));
               
                String tx5 = (res.getString(5));
               
                String tx6 = (res.getString(6));
                
                String tx7 = (res.getString(7));
                
                Object tx8 = ((String)res.getObject(8));
                
               
                jtRG.setText(tx1);
                jtNome.setText(tx2);
                jtData.setText(tx3);
                jtEmail.setText(tx4);
                jtCelular.setText(tx5); 
                jtTelefone.setText(tx6);
                jtSenha.setText(tx7);
                Combo.setSelectedItem(tx8);
                ;
                 
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCelularActionPerformed

    private void jtRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtRGActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> Combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNome1;
    private javax.swing.JLabel jlQuantidade;
    private javax.swing.JLabel jlQuantidade1;
    private javax.swing.JLabel jlQuantidade2;
    private javax.swing.JLabel jlQuantidade3;
    private javax.swing.JLabel jlValorCusto;
    private javax.swing.JLabel jlValorCusto1;
    private javax.swing.JFormattedTextField jtCPF;
    private javax.swing.JFormattedTextField jtCelular;
    private javax.swing.JFormattedTextField jtData;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNome1;
    private javax.swing.JTextField jtQuantidade1;
    private javax.swing.JFormattedTextField jtRG;
    private javax.swing.JPasswordField jtSenha;
    private javax.swing.JFormattedTextField jtTelefone;
    private javax.swing.JTextField jtValorCusto2;
    private javax.swing.JTextField jtValorCusto3;
    // End of variables declaration//GEN-END:variables
}
