/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import Vo.Reserva;
import dao.ReservarDao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author haduk
 */
public class VisuReservas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VisuReservas
     */
    public VisuReservas() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) TableReserva.getModel();
        TableReserva.setRowSorter(new TableRowSorter(modelo));
        readTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableReserva = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Reservas");

        TableReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "CPF", "Pessoas", "Valor", "Tipo", "Check_in", "Check_in", "Frigobar", "Bar", "Quant Bar", "Confirmar_Checkin", "Confirmar_Checkout"
            }
        ));
        jScrollPane1.setViewportView(TableReserva);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Excluir");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Reserva hosp= new Reserva();
      if(TableReserva.getSelectedRow() != -1){
     hosp.setCod((int) TableReserva.getValueAt(TableReserva.getSelectedRow(),0));
     ReservarDao dao = new ReservarDao();
     dao.deletar(hosp);
     readTable();}else{
          JOptionPane.showMessageDialog(null,"Selecione uma Reserva para excluir");
      }       
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                       
  Reserva pVO = new Reserva();
    pVO.setCod((int) TableReserva.getValueAt(TableReserva.getSelectedRow(),0)) ; 
   pVO.setCpf( TableReserva.getValueAt(TableReserva.getSelectedRow(),1).toString()) ; 
    pVO.setNum((int) TableReserva.getValueAt(TableReserva.getSelectedRow(),2)) ; 
    pVO.setValor((double) TableReserva.getValueAt(TableReserva.getSelectedRow(),3)) ; 
    pVO.setTipo( TableReserva.getValueAt(TableReserva.getSelectedRow(),4).toString()) ; 
    pVO.setCheckin( TableReserva.getValueAt(TableReserva.getSelectedRow(),5).toString()) ; 
    pVO.setCheckout( TableReserva.getValueAt(TableReserva.getSelectedRow(),6).toString()) ; 
    pVO.setFrigobar( TableReserva.getValueAt(TableReserva.getSelectedRow(),7).toString()) ; 
    pVO.setBar( TableReserva.getValueAt(TableReserva.getSelectedRow(),8).toString()) ; 
    pVO.setBarnum((int) TableReserva.getValueAt(TableReserva.getSelectedRow(),9)) ; 
    pVO.setConfirmar1(TableReserva.getValueAt(TableReserva.getSelectedRow(),10).toString()) ; 
    pVO.setConfirmar2((String) TableReserva.getValueAt(TableReserva.getSelectedRow(),11)) ;
    
   
            
            //Enviando o objeto pVO para o banco de dados
            ReservarDao dao = new ReservarDao();
dao.atualizarReserva(pVO);
readTable();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
 public void readTable(){
       DefaultTableModel modelo = (DefaultTableModel) TableReserva.getModel();
        modelo.setNumRows(0);
       ReservarDao qd = new ReservarDao();
       for(Reserva q: qd.read()){
           
            modelo.addRow(new Object[]{
                
             q.getCod (),
                q.getCpf(),
                q.getNum(),
                q.getValor(),
                q.getTipo(),
                q.getCheckin(),
                q.getCheckout(),
                q.getFrigobar(),
                q.getBar(),
                q.getBarnum(),
                q.getConfimar1(),
                q.getConfimar2(),
            });
       }
       
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableReserva;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
